### ISSUE TITLE
도전과제 brainDiver의 설명은 cherrypick에서 misskey로 복구하는것이 어울릴 것 같습니다

### ISSUE THREAD

**Issue by kdh8219** [kokonect-link/cherrypick#399]
노래가사니까 원래대로 두는게 좋을 것 같아요...!
https://github.com/kokonect-link/cherrypick/blob/9260653dafa97d16079a5bbe9122909ba0a41314/locales/ko-KR.yml#L1727
https://github.com/kokonect-link/cherrypick/blob/9260653dafa97d16079a5bbe9122909ba0a41314/locales/no-NO.yml#L540
https://github.com/kokonect-link/cherrypick/blob/9260653dafa97d16079a5bbe9122909ba0a41314/locales/fr-FR.yml#L1327
https://github.com/kokonect-link/cherrypick/blob/9260653dafa97d16079a5bbe9122909ba0a41314/locales/ja-JP.yml#L1756
https://github.com/kokonect-link/cherrypick/blob/9260653dafa97d16079a5bbe9122909ba0a41314/locales/ja-KS.yml#L1485
https://github.com/kokonect-link/cherrypick/blob/9260653dafa97d16079a5bbe9122909ba0a41314/locales/zh-TW.yml#L1538
https://github.com/kokonect-link/cherrypick/blob/9260653dafa97d16079a5bbe9122909ba0a41314/locales/es-ES.yml#L1444
https://github.com/kokonect-link/cherrypick/blob/9260653dafa97d16079a5bbe9122909ba0a41314/locales/id-ID.yml#L1444
https://github.com/kokonect-link/cherrypick/blob/9260653dafa97d16079a5bbe9122909ba0a41314/locales/uk-UA.yml#L1144
https://github.com/kokonect-link/cherrypick/blob/9260653dafa97d16079a5bbe9122909ba0a41314/locales/zh-CN.yml#L1436
https://github.com/kokonect-link/cherrypick/blob/9260653dafa97d16079a5bbe9122909ba0a41314/locales/en-US.yml#L1731
https://github.com/kokonect-link/cherrypick/blob/9260653dafa97d16079a5bbe9122909ba0a41314/locales/de-DE.yml#L1461

**Comment by noridev** [comment]
ce7d5c0db0284ca62be51b32a660842c7852d02d 에서 해결되었습니다. 감사합니다!
