### ISSUE TITLE
노트 자세히보기 창 아래의 답글란에 답글을 적을 경우에도 자동적으로 맨션을 추가.

### ISSUE THREAD

**Issue by kdh8219** [kokonect-link/cherrypick#401]
### Summary

노트 자세히보기 창의 아래에 있는 답글란에 답글을 적어 투고할 경우 답글버튼을 눌러 답글을 적는것과 상이하게, 노트 작성자가 자동으로 맨션으로 추가되지 않음.
따라서, 해당란에 답글을 작성할 때도 자동적으로 맨션을 추가해야 함.
ex)
![image](https://github.com/kokonect-link/cherrypick/assets/65698239/c9533f32-b958-4aec-8b9d-f59208ef5f7f)

### Purpose

일관적 동작

**Comment by noridev** [comment]
최신 커밋에서 수정되었습니다! 감사합니다!
