### ISSUE TITLE
タイムライン上の投稿フォームでプレビューをオンにしてリンクを含む投稿をした後、そのリンク先の説明がプレビューに残っている。

### ISSUE THREAD

**Issue by natumi-kaoru** [kokonect-link/cherrypick#403]
### 💡 Summary

標記の通りです。
「タイムライン上部に投稿フォームを表示する」を入にしておき、その投稿フォームでプレビューをオンにし、リンクを含むノートを投稿したら（図１）、投稿フォームは空になっているにも関わらず、プレビューにはそのリンク先の説明が残っています（図２）。
![図１](https://github.com/kokonect-link/cherrypick/assets/145369415/c997d561-2bfd-4628-b4e3-0009400d1c19)
![図２](https://github.com/kokonect-link/cherrypick/assets/145369415/e87ca586-116f-40f2-a7bd-a29686f6e1eb)

### 🥰 Expected Behavior

リンクを含むノートを投稿しても、投稿フォームの内容が空っぽになるのと同じように、リンク先の説明も含めてプレビューは空っぽになる。

### 🤬 Actual Behavior

リンクを含むノートを投稿したら、投稿フォームの内容が空っぽになるのに対して、リンク先の説明がプレビューに残っている。

### 📝 Steps to Reproduce

1. 「設定」→「クライアント説明/全般」で、「タイムライン上部に投稿フォームを表示する」を入にする。
2. タイムライン上部の投稿フォームで、「本文をプレビュー」を入にし、リンクを含むノートを投稿する。

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Windows 11 23H2
* Browser: Chrome 120.0.6099.199
* Server URL: https://love.xn--vusz0j.life/ , https://m.tkngh.jp/
* CherryPick: 4.5.2, 4.6.0-beta.6
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* CherryPick:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by noridev** [comment]
https://github.com/kokonect-link/cherrypick/commit/bc1f0a93026c460389b628eb38083bfdd968076e で修正しました。ありがとうございます！🙏🙏

**Comment by natumi-kaoru** [comment]
すばやいご修正、ありがとうございます☺️
