### ISSUE TITLE
リノート範囲を事前に設定する機能

### ISSUE THREAD

**Issue by penginn-0** [kokonect-link/cherrypick#406]
### Summary

リノート確認ポップアップとリノート公開範囲表示が無効の時、設定で範囲を設定する機能がほしいです

### Purpose

リノート公開範囲をポップアップなしに指定できると便利なため。

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by noridev** [comment]
同じ機能を考えていました。
ポップアップなしで押すために存在する機能なのに、ポップアップが出てきて私も不便でした。

**Comment by noridev** [comment]
機能の追加が完了しました。ありがとうございました！
