### ISSUE TITLE
ウィンドウでコントロールパネルを開いたとき、ウィンドウ内の←ボタンを押すと戻る

### ISSUE THREAD

**Issue by penginn-0** [kokonect-link/cherrypick#407]
### 💡 Summary

ウィンドウ内の←ボタンを押すとデッキのメインカラムか表示しているページが戻る
![image](https://github.com/kokonect-link/cherrypick/assets/121443048/0f1de668-9bda-4c7f-8b03-eb800312c854)

### 🥰 Expected Behavior

ウィンドウの枠の←と同じ挙動

### 🤬 Actual Behavior

ウィンドウ内の←ボタンを押すとデッキのメインカラムか表示しているページが戻る

### 📝 Steps to Reproduce

1.コントロールパネルの画面内に←がある項目を開く
2.←を押す
3.戻る

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):Windows 10 22H2 (19045.3803)
* Browser:Chrome 120.0.6099.130
* Server URL:https://love.xn--vusz0j.life/
* CherryPick:4.6.0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* CherryPick:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by noridev** [comment]
026e101c14ec48f0110fa543be502f51243253c8 で修正しました。ありがとうございます！🙏🙏
