### ISSUE TITLE
コードをコピーするとコピーと同時に移動する

### ISSUE THREAD

**Issue by penginn-0** [kokonect-link/cherrypick#414]
### 💡 Summary

ノートのコードをコピーすると移動する

### 🥰 Expected Behavior

ノートのコードをコピーしても移動しない(ウィンドウを開かない)

### 🤬 Actual Behavior

ノートのコードをコピーすると移動する

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:Chrome
* Server URL:love.xn--vusz0j.life /m.tkngh.jp
* CherryPick:4.7.0-beta.1
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* CherryPick:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by penginn-0** [comment]
https://github.com/kokonect-link/cherrypick/assets/121443048/f9075ec0-1479-420d-8862-b3793b6652f5

**Comment by noridev** [comment]
コピーボタンはChromeで独自にサポートしているのでしょうか？

**Comment by penginn-0** [comment]
コピーボタンは↓で追加された機能です
misskey-dev/misskey/issues/12985
misskey-dev/misskey/pull/12999

**Comment by noridev** [comment]
af5803d0deb2265e1f7d78e2fe75e48d81a1e48f で修正しました。ありがとうございます！🙏🙏
