### ISSUE TITLE
현재 어떤 타임라인에 있는지 표시하는 부분이 창의 크기를 변경할 때 따라오지 못합니다.

### ISSUE THREAD

**Issue by sunwoo1524** [kokonect-link/cherrypick#415]
### 💡 Summary

현재 어떤 타임라인에 있는지 표시하는 부분이 창의 크기를 변경할 때 따라오지 못합니다.

### 🥰 Expected Behavior

미스키의 경우, 창 크기를 바꿔도 현재 어떤 타임라인에 있는지 잘 표시됩니다.

### 🤬 Actual Behavior

하지만 체리픽의 경우 창 크기를 따라오지 못하고 제자리에 있습니다.
글로 설명하기는 어려운 것 같아 녹화한 동영상을 공유하겠습니다.

https://github.com/kokonect-link/cherrypick/assets/108212889/117a67a9-a8fc-4d32-a039-7b47ce819a49

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Arch Linux, GNOME
* Browser: Firefox, Chromium
* Server URL: https://worldc.one
* CherryPick: 4.6.0, 4.7.0-beta.1
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* CherryPick:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by noridev** [comment]
ebc966609633f1789f0b1153e05f5784c771943d 에서 수정되었습니다! 감사합니다 :) 🙏🙏
