### ISSUE TITLE
アカウント統計が見れない

### ISSUE THREAD

**Issue by penginn-0** [kokonect-link/cherrypick#416]
### 💡 Summary

アカウント統計を開くと見つかりませんでしたが表示されます

### 🥰 Expected Behavior

アカウント統計が見れる

### 🤬 Actual Behavior

アカウント統計が見れない

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:love.xn--vusz0j.life,m.tkngh.jp
* CherryPick:4.7.0-beta1
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* CherryPick:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by noridev** [comment]
4f52a38116ec4e6bca86a75e9cc2e8ce6b7f9c20 で修正しました。ありがとうございます！🙏🙏
