### ISSUE TITLE
설정 - 알림에서 테스트 알림을 생성할 수 없음

### ISSUE THREAD

**Issue by ltlapy** [kokonect-link/cherrypick#422]
### 💡 Summary

CherryPick Web에서 [설정 - 알림]을 통해 테스트 알림 생성 버튼을 클릭해도 아무런 반응이 없으며, 테스트 알림이 생성되지 않습니다.

### 🥰 Expected Behavior

알림에 테스트 알림 항목이 생성됩니다.

### 🤬 Actual Behavior

아무런 반응이 없으며, 개발자용 콘솔에서 `TypeError: Cannot read properties of undefined (reading '0')` 이라는 메시지가 표시됩니다.

### 📝 Steps to Reproduce

1. 정상적인 CherryPick 계정을 사용하여 Web 클라이언트로 접속
2. 설정 - 알림에서 '테스트 알림 보내기' 클릭

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Windows 11 23H2
* Browser: Microsoft Edge 121.0.2277.128 (공식 빌드) (64비트)
* Server URL: https://k.lapy.link/ and https://stella.place/
* CherryPick: 4.7.0-beta.3 and 4.6.0+cs-7a02ecb

> Misskey 2024.2.0에서 동일한 문제가 발생하지 않는 것을 확인했습니다
```

### 🛰 Backend Environment (for server admin)

```markdown
> https://k.lapy.link 의 경우
* Installation Method or Hosting Service: docker compose
* CherryPick: 4.7.0-beta.3
* Node: *
* PostgreSQL: *
* Redis: *
* OS and Architecture: *
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by ltlapy** [comment]
관련 파일: https://github.com/kokonect-link/cherrypick/blob/5e2168dbddfee67bfde397e34e34bcbdd5f1aa6a/packages/frontend/src/pages/settings/notifications.vue#L117

`notifications/test-notification` API를 직접 때리면 정상적으로 작동하는데, UI 상 버튼을 누르면 반응이 없고, API 요청도 날아가지 않는군요

**Comment by noridev** [comment]
vue상 코드는 Misskey의 것을 그대로 붙여 넣어도 작동하지 않는 걸 보면, 다른 부분에서 문제가 있는 것 같은데 도통 원인을 모르겠군요...
저 문제와 동일한 이유로 읽음 표시도 작동하지 않고 있네요..🥲

**Comment by noridev** [comment]
319a5370cdc40844cbc126c674471c0fee2f7895 에서 수정되었습니다!
