### ISSUE TITLE
タイムラインでアイコンを押すと画面が真っ黒になる

### ISSUE THREAD

**Issue by 16439s** [kokonect-link/cherrypick#451]
### 💡 Summary

CherryPick 4.8.0-beta.2にて
タイムラインでアイコンを押すと、画面が真っ黒になります。
詳しくは添付ファイルを見てほしいです。

https://github.com/kokonect-link/cherrypick/assets/146170742/9cb1fb9f-9f41-4928-967d-49bd5fc8d769

### 🥰 Expected Behavior

アイコンを押すと、その人のプロフィール欄に移動する

### 🤬 Actual Behavior

アイコンを押すと画面が真っ黒になる

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Galaxy S23 / One UI 6.0（Android 14）
* Browser:Google Chrome（WebView）
* Server URL:https://beta.kokonect.link
* CherryPick:4.8.0-beta.2
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* CherryPick:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by SWREI** [comment]
This also happens for mention & hashtags, username in content. related to "click to open detailed note view"

**Comment by 16439s** [comment]
> This also happens for mention & hashtags, username in content. related to "click to open detailed note view"

I see.
Do you have any idea which commit are the cause?

**Comment by SWREI** [comment]
> > This also happens for mention & hashtags, username in content. related to "click to open detailed note view"
> 
> I see. Do you have any idea which commit are the cause?

https://github.com/kokonect-link/cherrypick/commit/d6fa889c936efd778b2bc25de9629ff0a5cb4f3c
this is click note to view detailed page

https://github.com/kokonect-link/cherrypick/commit/fc77ae6f45c5b7ab7954c411f5771dbc811057c2
and this commit fixed this issue

but while merging upstream, maybe @noridev didn't check this so it was reset to `@click.stop` to `@click` how Misskey works like.

needs to fix this with re-applying these code, or just refactor "click to view note detail" feature at all.

**Comment by SWREI** [comment]
> Apple環境(iOS、iPadOS)およびPC環境では確認できていません。
> Android環境でのみ問題が発生しますか？

사실 이 문제는 정확히는 아바타 (또는 유저명, 멘션, 해시태그 등...) 를 클릭해서 노트 상세 페이지에 진입 시 아주 짧은 시간 동안 가야 하는 페이지로 진입 후 이후 parent 컴포넌트의 영향으로 해당 페이지가 불러와지기 전에 `/notes/:id` 페이지로 즉시 이동되어 페이지가 제대로 불러와지지 않는 문제로 보입니다. 그래서 원하는 페이지로 가기 위해 해당하는 컴포넌트를 다시 클릭하거나, 브라우저 자체 뒤로 버튼을 이용해도 동일한 문제가 발생합니다. 그리고 그 이후로는 어떤 걸 눌러도 새로고침 전까지는 페이지를 불러오지 못하는 문제로 이어지게 됩니다.

물론 페이지를 이동하려고 다시 시도하는 대신 네비게이션 바에서 타임라인으로 돌아가거나, 다른 링크로 이동하는 경우 해당 문제는 발생하지 않습니다.

본 문제는 Windows 11 환경의 Chrome 124.0.6367.119 버전 환경 및 iOS 17.5 Developer Beta의 Safari에서도 재현이 가능했습니다.

![iOS](https://space.psec.dev/local/fcc311ba-1969-4f95-b1c1-7744082868cf.png)
![Windows](https://space.psec.dev/local/05ac5516-27ed-4c3e-bbce-06350e84a909.png)

**Comment by noridev** [comment]
6059ea407878e29de96c944515d29eb1a318d3a3 で修正しました。ありがとうございます！🙏🙏
