### ISSUE TITLE
CherryPickのチャット機能を使って Mastodonにメッセージを送るとバグる

### ISSUE THREAD

**Issue by mirielnet** [kokonect-link/cherrypick#459]
### 💡 Summary

CherryPickのチャット機能を使って Mastodonにメッセージを送ると、メッセージの末尾に #objectobject という文字が出ます。
それは非常に不快であり、心配を引き起こします。
![image](https://github.com/kokonect-link/cherrypick/assets/168396067/b8f0cb3d-668b-46c1-a97f-fbe9e1b52bf6)

### 🥰 Expected Behavior

#objectobject が出ない

### 🤬 Actual Behavior

#objectobject が出る

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser: 関係なし
* Server URL:https://beta.kokonect.link
* CherryPick:4.8.0-beta.2
```

### 🛰 Backend Environment (for server admin)

```markdown
* CherryPick:4.8.0-beta.2
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by SWREI** [comment]
tags parameter contains `{}` and maybe this has been converted to `[object Object]` in ApRenderService.

https://github.com/kokonect-link/cherrypick/blob/03bbd93c36a020aaa3389f46a965475fb17c837e/packages/backend/src/core/MessagingService.ts#L133-L149

**Comment by noridev** [comment]
646f21d008bb8c84fc54b3bd08980bd45c86898f で修正しました。ありがとうございます！🙏🙏
