### ISSUE TITLE
コードブロックの表示と実際に文字が入力される位置がずれている。

### ISSUE THREAD

**Issue by natumi-kaoru** [kokonect-link/cherrypick#475]
### 💡 Summary

Playのコードの入力画面やカスタムCSSの設定画面で、フォントの表示されている位置と実際の文字の位置がずれています。
これによって、コードの入力に支障をきたしてしまっています。

画像はドラッグで文字選択して、実際の文字の位置を表示させた様子です。
![スクリーンショット](https://github.com/kokonect-link/cherrypick/assets/145369415/3d2c90f0-0f7c-48e1-b715-079f80d4d6cf)

### 🥰 Expected Behavior

フォントの表示されている位置と実際の文字の位置が一致する。

### 🤬 Actual Behavior

フォントの表示されている位置と実際の文字の位置が一致せず、文字を入力したときにカーソルと違う位置に入力したことになる。

### 📝 Steps to Reproduce

1. Playの編集画面を開くか、カスタムCSSの設定画面を開く。
2. 任意の位置（ブロックの下の方で顕著に起こる）に文字を入力する。

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): DELL Inspiron 3505, Windows 11 Home 23H2
* Browser: Google Chrome 126.0.6478.127
* Server URL: https://m.tkngh.jp/
* CherryPick: 1.0-b4.7.0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* CherryPick:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by mirielnet** [comment]
Same as 1.0-b4.7.0=4.9.0-beta.2.
No changes.
@noridev

**Comment by natumi-kaoru** [comment]
> Same as 1.0-b4.7.0=4.9.0-beta.2. No changes. @ noridev

Thank you.

**Comment by 1673beta** [comment]
Related?: https://github.com/misskey-dev/misskey/issues/12927

**Comment by noridev** [comment]
c8626912a0983a3e1e0ce9db02b0cf7ad03269f6 で修正しました。ありがとうございます！🙏🙏
