### ISSUE TITLE
リアクションビューワーから絵文字をインポートしようとするとエラーが発生する

### ISSUE THREAD

**Issue by 1673beta** [kokonect-link/cherrypick#487]
### 💡 Summary

![image](https://github.com/user-attachments/assets/74b49d36-2fe2-4afb-b04e-a1358249fcce)
画像のようにリアクションビューワー上に絵文字が存在する場合、クリックしてインポートしようとするとNo such emojisが出る

### 🥰 Expected Behavior

インポートできる(admin/emoji/stealに正しくパラメータが伝わる)

### 🤬 Actual Behavior

インポートできない

### 📝 Steps to Reproduce

1. リアクションビューワーからリアクションをインポートする

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): macOS 14.6
* Browser: Vivaldi 6.8
* Server URL: c.koliosky.com
* CherryPick: 4.10.0-rc.3-engawa.0.5.0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* CherryPick:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [X] Yes, I will patch the bug myself and send a pull request

**Comment by noridev** [comment]
CherryPick `4.10.0-rc.3`バージョンを基準とする`beta.kokonect.link`では、この問題が再現されていません。
CherryPickの改造バージョンではなく、修正が加えられていないCherryPickと新しいDBでテストを進めていただけますか？

**Comment by 1673beta** [comment]
CherryPick 4.10.0-rc.4で再現しました。
![202408311131_cherrypick_test](https://github.com/user-attachments/assets/4469b837-2eda-4ff6-baa9-282233c75fc5)

**Comment by 1673beta** [comment]
> CherryPick 4.10.0-rc.3バージョンを基準とするbeta.kokonect.linkでは、この問題が再現されていません。
ノートとインポートしようとしているリアクションが同一hostだと発生しないようですが(ノートのhostとMkReactionViewer.reaction.vueのprops.note.reaction.hostが一致するため)、それぞれが違うホストの場合発生しませんか？

**Comment by noridev** [comment]
該当エラーが 06faf6c6a60eb774e7875f7e152b0ec7a2b4dd2f で修正されました。ありがとうございます！🙏
