### ISSUE TITLE
4.11.0으로 업데이트 이후 더보기탭이 전혀 작동되지않음

### ISSUE THREAD

**Issue by kassiyaaa** [kokonect-link/cherrypick#492]
### 💡 Summary

체리픽 4.11.0 업데이트 이후로 더보기 탭이 전혀 작동하고 있지 않습니다.
어디서 문제가 된건지는 제가 보지 못하는 상황입니다. 

### 🥰 Expected Behavior

https://github.com/user-attachments/assets/687cf517-5a44-482b-a5b6-795b6dfd19ea

### 🤬 Actual Behavior

https://github.com/user-attachments/assets/7423e89f-d4e2-4c1d-b292-6211febe56e5

### 📝 Steps to Reproduce

1. 더보기 탭이 정상작동이 확인 되는가
2. 무엇이 문제인지 확인하신 후에 수정부탁드립니다.

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Windows 11, Endeavour OS
* Browser: Firefox, Chrome, Microsoft Edge, LibreWolf
* Server URL:kokonect.link
* CherryPick:4.11.0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* CherryPick:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by noridev** [comment]
`4.11.1`에서 해당 문제가 수정되었습니다! 감사합니다! 👍
