### ISSUE TITLE
Is it possible to implement having the "Including Files" tab in a grid layout?

### ISSUE THREAD

**Issue by heepolemons** [kokonect-link/cherrypick#494]
### Summary

Hello, 

Is it possible to implement having the "Including Files" tab in a grid layout? Back in Mastodon, "Media" tabs in peoples' profiles were laid out in a grid, making it highly convenient to look for specific or old artworks. Misskey and its forks do not have it, however.

Sincerely,
Lemonheep

### Purpose

I feel that it would most for browsing through artists' profiles. Oftentimes, older artworks are still really fascinating, so it sucks to see them lost in a sea of newer posts.

![Screenshot from 2024-09-16 03-24-09](https://github.com/user-attachments/assets/edc02c0a-f8ac-4976-91b2-1ccaefdcdf33)

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by noridev** [comment]
Function implementation completed in 01351529e9e75e134b69608ae29f12f913895c99. Thank you! 🙏

**Comment by heepolemons** [comment]
Thank you! ❤️
