### ISSUE TITLE
in-feed post tweak options

### ISSUE THREAD

**Issue by breadguyyy** [kokonect-link/cherrypick#495]
### Summary

-option to show replied-to notes without grey filter
-option to collapse replied-to notes in feed
-option to always open the full conversation when opening a post
-option to always uncollapse CWs
-option to always uncollapse long posts

### Purpose

adds the ability for users (me specifically) to tailor the feeds to be easier to read and browse

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by noridev** [comment]
Can you elaborate on the "option to show replied-to notes without grey filter"?
Does it mean that the notes get greyer as they go down, when they are long or have items that affect the federation?

**Comment by breadguyyy** [comment]
> Can you elaborate on the "option to show replied-to notes without grey filter"? Does it mean that the notes get greyer as they go down, when they are long or have items that affect the federation?

sorry I'm not explaining it right I mean how the notes that are replied to are greyed out, makes it hard to read without opening the whole thread. example:

![Screenshot_20241001-053943](https://github.com/user-attachments/assets/f28f52c7-2fae-4c1e-bdb5-3daac41a55ae)

**Comment by noridev** [comment]
I understand :)
To prevent timeline terrorism and readability, notes longer than 500 characters or longer than 9 lines are automatically hidden.

This is Misskey's standard, and I think it's better to keep it if possible, but there may be users who want to tolerate this and set it to show all the contents.

CherryPick is designed to give users a choice in this conflict of opinions.

Therefore, I plan to add a feature to unconditionally expand the contents regardless of the conditions, but the default will be set to off to prevent the above problem.

**Comment by breadguyyy** [comment]
nice! To clarify though, I mean that those posts are greyed out even when expanded. might be hard to tell in the screenshots but you can see that the title bar and post text of the first note are darker than in the one below it

**Comment by breadguyyy** [comment]
using the new patch and it's a game changer for me thank you so much!! 
I have a couple of notes:
-by "collapse notes replied to" I meant the reply target notes
-reply target notes seem to have smaller text and cramped usernames on the new patch
-files are still collapsed in them as well, even with all the collapse settings disabled
![Screenshot_20241001-121316](https://github.com/user-attachments/assets/3aed141e-a22b-4850-a3d8-88a8ba2c6084)

**Comment by noridev** [comment]
reply target notes seem to have smaller text
-> To make it easier to distinguish between content, the font size of the reply target note is set to be displayed smaller.
This somewhat solves the problem of it being difficult to distinguish between replies and original text in long notes.

usernames seem to be horizontally cramped on the new patch
-> This is a change made in Misskey's 2024.9.0.
You can disable this feature in 'Settings - Other - Experimental features - Enable condensed line'.

**Comment by breadguyyy** [comment]
ahhh I see thank you!!

**Comment by noridev** [comment]
files are still collapsed in them as well, even with all the collapse settings disabled
-> Could you elaborate a bit more on this issue?
It seems to be working fine in my environment.

<img width="1208" alt="image" src="https://github.com/user-attachments/assets/51ba78e9-1a8f-4929-a8f9-93a1b9eec933">

<img width="1201" alt="image" src="https://github.com/user-attachments/assets/a2b732c3-bf85-4297-a878-aece1b54234a">

**Comment by breadguyyy** [comment]
![Screenshot_20241001-140544](https://github.com/user-attachments/assets/83a728a6-4c08-45c7-a92d-5090bca6ced5)
![Screenshot_20241001-140522](https://github.com/user-attachments/assets/6e8ef13a-95b5-411c-87a4-e2f9c8bd08a5)
maybe it's only an issue on mobile?
pixel 8a, Vivaldi pwa

**Comment by noridev** [comment]
The problem is not reproduced in my mobile environment... :(
My Android 14, Chrome PWA environment did not reproduce the same issue.

![telegram-cloud-photo-size-5-6332098026142811475-y](https://github.com/user-attachments/assets/69ad36d0-a19f-48a1-848e-3db929f2a566)
![telegram-cloud-photo-size-5-6332098026142811476-y](https://github.com/user-attachments/assets/9e17e714-5950-4010-8d52-6ba2d5650803)

**Comment by breadguyyy** [comment]
so odd I turned it on, cleared cache, turned it back off, cleared cache, and idk I can't get it to show automatically. we're on beta 4 btw

**Comment by breadguyyy** [comment]
just noticed another thing, notes still have partial transparency when revealed by the "show conversation" button

**Comment by breadguyyy** [comment]
> maybe it's only an issue on mobile? pixel 8a, Vivaldi pwa
finally tested on desktop, getting the same issue. i believe it's only reply targets with text and media that remain collapsed

**Comment by noridev** [comment]
The development of the requested features has been completed.
In addition, the issue where some reply target notes were transparent has been fixed.

Since the implementation of the features has been completed, this issue will be closed for now. If any errors occur in the future, please create a new issue. :)

If a problem occurs with a specific feature, please test whether the problem occurs at [beta.kokonect.link](https://beta.kokonect.link) to control variables and identify the cause.

- [x] option to show replied-to notes without grey filter
- [x] option to collapse replied-to notes in feed
- [x] option to always open the full conversation when opening a post
- [x] option to always uncollapse CWs
- [x] option to always uncollapse long posts
