### ISSUE TITLE
alt text warning

### ISSUE THREAD

**Issue by breadguyyy** [kokonect-link/cherrypick#499]
### Summary

add an option to warn when posting media without alt text

### Purpose

it's easy to forget to put alt text, it's helpful to have a reminder

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by noridev** [comment]
Function implementation completed in d7da3e6198df8c2c73f6a2e3d4f114164544511a. Thank you! 🙏
