### ISSUE TITLE
hide like button

### ISSUE THREAD

**Issue by breadguyyy** [kokonect-link/cherrypick#501]
### Summary

add option to hide the default like button like vanilla misskey

### Purpose

to me, the like button is redundant with the emoji react button since it serves the same purpose

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by noridev** [comment]
Function implementation completed in e4b2da4fb8dec590d7c70262d71d96bb11dc88f4. Thank you! 🙏
