### ISSUE TITLE
domain mute/block button

### ISSUE THREAD

**Issue by breadguyyy** [kokonect-link/cherrypick#502]
### Summary

add a button in the user menu to quickly add their instance to the mute/block list

### Purpose

more self moderation tools are always welcome

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by noridev** [comment]
Function implementation completed in 61bfadc2867846aba34eba3c073070f2f6e92be5 and 61bfadc2867846aba34eba3c073070f2f6e92be5. Thank you! 🙏

**Comment by noridev** [comment]
I'm re-closing this issue as functionality for general users has been added.
