### ISSUE TITLE
Mentions of users with . in their usernames aren't rendered correctly

### ISSUE THREAD

**Issue by FitikWasTaken** [kokonect-link/cherrypick#509]
### 💡 Summary

Any mentions of users with . in their usernames are getting cut after the dot. According to the webfinger specs these 4 symbols are allowed: _ - . ~ ( https://www.w3.org/community/reports/socialcg/CG-FINAL-apwf-20240608/#names )

CherryPick supports the first two, and I have never seen a Fediverse software that supports creating an account with a tilde

However, there are examples of accounts with a dot using different software:

Bridgy Fed: @bsky.brid.gy@bsky.brid.gy
Threads: @johannes.ernst@threads.net
PeerTube: @alison.wake@makertube.net

### 🥰 Expected Behavior

It should be rendered as a normal mention.

It was fixed in Sharkey, there's a related Sharkey commit: https://activitypub.software/TransFem-org/sfm-js/-/commit/3b5bfe6f6a1701e9abfcd4e7f97a4ff348d6ffbe

### 🤬 Actual Behavior

It's getting cut and username that should look like @cool.name@remote.instance is rendered as @cool@local.instance.name@remote.instance and it's definitely incorrect

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Unrelated
* Browser: Firefox
* Server URL: kitty.social
* CherryPick: 4.12.0-beta.9
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by noridev** [comment]
A Solve to this issue has been completed in `kokonect-link/cfm.js`.
