### ISSUE TITLE
navigation bar configuration 

### ISSUE THREAD

**Issue by breadguyyy** [kokonect-link/cherrypick#510]
### Summary

would love to be able to set which buttons are shown on the bottom navigation bar, for example I was hoping to replace the explore button with the search button

### Purpose

more user experience customization 👍

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by noridev** [comment]
Function implementation completed in 36c922fbddbb8fb6ad1b3d777a255548608da8f6. Thank you! 🙏
