### ISSUE TITLE
사진 위로 마우스를 가져가면 대체 텍스트는 표시되지 않지만 파일 이름은 표시됩니다.  ( When you hover over a photo, the alt text is not displayed, but the filename is.)

### ISSUE THREAD

**Issue by Linux-Is-Best** [kokonect-link/cherrypick#514]
### 💡 Summary

“CherryPick"와 ‘Misskey’를 비교합니다. 사진 위로 마우스를 가져가면 대체 텍스트가 표시되는 것을 볼 수 있습니다. 현재 이 기능은 최신 버전인 'CherryPick'에서는 제대로 작동하지 않습니다. 

Comparing CherryPick alongside Misskey. You can see the Alt Text is meant to show up when you hover your mouse over a photo. This is not currently correctly working in the latest version of CheryPick. 

![alt_text](https://github.com/user-attachments/assets/e50e463a-10b5-433a-a3ac-230ae9b523e1)
![alt_text2](https://github.com/user-attachments/assets/515cf839-7f03-4478-85b2-852d62e6b05f)

### 🥰 Expected Behavior

컴퓨터 마우스를 사진 위로 가져가면 대체 텍스트가 표시됩니다.

Alternative text appears when you hover your computer mouse over a photo.

### 🤬 Actual Behavior

컴퓨터 마우스 위에 마우스를 가져가면 파일 이름이 표시됩니다.

When you hover over the computer mouse, the file name is displayed.

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Arch Linux (Desktop)
* Browser: Vivaldi
* Server URL: https://kokonect.link/notes/9z1ogvqovdf200ik
* CherryPick:  4.12.0
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by noridev** [comment]
The issue has been fixed in c237b64b073dead93c3cc8ecd1bb6c5e26030644. Thank you! 🙏
