### ISSUE TITLE
Editing local only post is federated

### ISSUE THREAD

**Issue by ltlapy** [kokonect-link/cherrypick#519]
### 💡 Summary

로컬 전용 게시물에 대한 편집이 연합되어, Misskey를 포함한 일부 리모트 서버에서 표시되는 문제가 발생

Related with: https://github.com/libnare/shiftkey/commit/c019ae872950cb79f2808c4cfeff5fc7fb44464c

### 🥰 Expected Behavior

로컬 전용 게시물을 편집해도 연합이 되지는 않는다
Editing local-only post does not affect to any of federation

### 🤬 Actual Behavior

로컬 전용 게시물에 대한 편집이 연합되어, 때에 따라 리모트 서버에 게시물이 표시된다
Editing local only post is federated as if it's not local-only post, resulting in some servers (including Misskey) display the edited post

### 📝 Steps to Reproduce

1. Have a least 1 remote follower
2. Write a post without federation
3. Edit the post
4. Check from remote follower

### 💻 Frontend Environment

```markdown
* CherryPick: 4.12.0
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by noridev** [comment]
87fc9c93997d9675e091cd7c98a2d9a4becbf2ac 에서 해당 이슈가 대응되었습니다! 감사합니다! 👍
