### ISSUE TITLE
frontend: 'Show more automatically replies' does not show the reply when reply is less than 3

### ISSUE THREAD

**Issue by ltlapy** [kokonect-link/cherrypick#521]
### 💡 Summary

> https://github.com/kokonect-link/cherrypick/commit/812b86943782beda41ac9c350a0e40917dbf7c6d 에서 추가된 '답글을 자동으로 더 보기'가, 답글이 3개 미만일 때에는 작동하지 않고 아무것도 표시되지 않아 답글 확인이 불가능함

https://k.lapy.link/notes/9zsyan8zh1

### 🥰 Expected Behavior

'답글을 자동으로 더 보기'가 답글이 1개나 2개일 때에도 정상적으로 보이거나, '답글 표시' 버튼이 표시되어 클릭하여 볼 수 있음

### 🤬 Actual Behavior

답글 탭 아래로 아무것도 표시되지 않음

### 📝 Steps to Reproduce

1. Turn on 'Show more automatically replies'
2. Create a note
3. Reply to the note (by anyone including author)
4. See a detailed view of the note (created at 2)

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Fedora Linux 40 (Workstation Edition)
* Browser: Thorium 126.0.6478.246(공식 빌드) stable, built on Ubuntu (AVX) (64비트)
* Server URL: https://k.lapy.link
* CherryPick: 4.12.0
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by noridev** [comment]
2f34456287016fa117ed593df7bb3226d962a5c6 에서 해당 문제가 수정되었습니다! 감사합니다! 👍
