### ISSUE TITLE
투표 기능 오작동

### ISSUE THREAD

**Issue by kaelz6516** [kokonect-link/cherrypick#523]
### Summary

![image](https://github.com/user-attachments/assets/bf76a425-8500-4693-aa9d-60b7c8be1a97)
투표에서 기간을 지정하면 작동되지 않고 바로 종료됨.
일시지정을 하면 작동됩니다. 기간지정시 문제가 생겨요.

### Purpose

-

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by noridev** [comment]
8e3c1f7f58fb62dfcd83daa4ecb652c94f58d92c 에서 수정되었습니다. 감사합니다! 🙏🙏
