### ISSUE TITLE
'답글을 자동으로 더보기' 옵션을 켜면 노트 타래가 안보이는 현상

### ISSUE THREAD

**Issue by jbblily** [kokonect-link/cherrypick#524]
### 💡 Summary

일반>'답글을 자동으로 더보기' 옵션이 켜져 있습니다. 아래에 멘션이 달려있고, 해당 멘션이 공개 상태임에도 타래가 보이지 않는 현상이 발생하고 있습니다.
옵션을 끄면 아래에 타래가 정상적으로 보입니다.

![스크린샷 2024-10-19 144112](https://github.com/user-attachments/assets/b1746fac-633a-46a1-959e-6c8eef56aaf1)
 -> '답글을 자동으로 더보기' 옵션을 켰을 때

![image](https://github.com/user-attachments/assets/d9be5db4-4eda-490b-81a2-b5bfe6f49dc5)
-> '답글을 자동으로 더보기' 옵션을 껐을 때

### 🥰 Expected Behavior

아래에 타래가 정상적으로 표시되어야 합니다.

### 🤬 Actual Behavior

타래가 보이지 않고 있습니다.

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Windows11
* Browser: Chrome
* Server URL: p.in-c.xyz
* CherryPick: 4.12.0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* CherryPick:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by noridev** [comment]
해당 이슈가 #521 에서 언급되어 이미 수정이 완료된 상태입니다.
이후 출시될 `4.12.1`에서는 기능을 정상적으로 이용하실 수 있습니다. 감사합니다. ☺️
