### ISSUE TITLE
add timeline settings to 3 dot menu

### ISSUE THREAD

**Issue by breadguyyy** [kokonect-link/cherrypick#528]
### Summary

![1000004868](https://github.com/user-attachments/assets/1a99c4ea-8c8e-4837-b937-2431a0e5866f)
![1000004869](https://github.com/user-attachments/assets/acb97423-d76d-4645-a1ff-27063c2f941b)
allow editing the timeline tabs right from the homepage

### Purpose

it just feels intuitive to have there

### Do you want to implement this feature yourself?

- [ ] Yes, I will implement this by myself and send a pull request

**Comment by noridev** [comment]
Function implementation completed in 466a7e0c89edb87b129edac3ecf5c0e72d4e5be3. Thank you! 🙏

**Comment by breadguyyy** [comment]
also might be good to add the custom cherrypick mobile header option there too!
