### ISSUE TITLE
titlebar gap

### ISSUE THREAD

**Issue by breadguyyy** [kokonect-link/cherrypick#535]
### 💡 Summary

video demonstrating the issue:
https://github.com/user-attachments/assets/0a7483d2-bd93-446f-b3be-ca530156c3dd
let me know if you need more info about my settings

### 🥰 Expected Behavior

no gap above titlebar

### 🤬 Actual Behavior

gap above titlebar when scrolled up

### 📝 Steps to Reproduce

open cherrypick and scroll (idk what to put here it seems specific to me or my browser)

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Pixel 8a, Android 15
* Browser: Vivaldi 7.0.3505.47
* Server URL: kitty.social
* CherryPick: 4.13.0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* CherryPick:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by noridev** [comment]
https://github.com/kokonect-link/cherrypick/issues/506
I will close this issue as it overlaps with the above content.
