### ISSUE TITLE
reply target note interactions require two taps

### ISSUE THREAD

**Issue by breadguyyy** [kokonect-link/cherrypick#536]
### 💡 Summary

in order to use the interaction buttons on a reply target note, I have to tap them twice

### 🥰 Expected Behavior

tapping the button does the interaction 

### 🤬 Actual Behavior

tapping the button once does nothing but haptics

### 📝 Steps to Reproduce

hit the like/react/reply/etc. button on a replied-to note

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s): Pixel 8a, Android 15
* Browser: Vivaldi 7.0.3505.47
* Server URL: kitty.social
* CherryPick: 4.13.0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* CherryPick:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by noridev** [comment]
🙏🙏
