### ISSUE TITLE
버블 타임라인 서버 입력칸 안 보임

### ISSUE THREAD

**Issue by jbblily** [kokonect-link/cherrypick#544]
### 💡 Summary

관리자 권한으로 버블 타임라인에 서버 주소를 입력하려 하는데, 입력칸이 표시되지 않습니다. (체리픽 4.14.0)
![image](https://github.com/user-attachments/assets/2f5dfc9f-5d09-4e0f-9d82-0bd4b0a4facf)

### 🥰 Expected Behavior

서버 입력칸이 표시되어야 함

### 🤬 Actual Behavior

칸이 안 보임

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser:
* Server URL:
* CherryPick:
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* CherryPick:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by 1673beta** [comment]
is it still happening when you enabled bubble timeline on base role?

**Comment by jbblily** [comment]
(slap face) Silly me... Solved it... Thank you!!!

**Comment by noridev** [comment]
버블 타임라인의 활성화 유무와는 상관없이 호스트 목록을 편집할 수 있어야 합니다.
해당 이슈는 버그가 맞으며, d4ab6800783999292c6a12a63c72791a2f7f9bcb 에서 수정되었습니다. 감사합니다! 🙏🙏
