### ISSUE TITLE
Navigation bar image not shown

### ISSUE THREAD

**Issue by jbblily** [kokonect-link/cherrypick#545]
### 💡 Summary

내비게이션 바의 배경에 이미지가 표시되지 않음
![스크린샷 2024-11-30 131901](https://github.com/user-attachments/assets/32678b86-b9e3-48eb-b4af-8a6a1637369e)
![스크린샷 2024-11-30 131926](https://github.com/user-attachments/assets/7c3aaa30-4354-4696-86ad-91573249380d)

### 🥰 Expected Behavior

서버 배너와 사용자 배너의 이미지가 내비게이션 바 배경에 표시되어야 함
![image](https://github.com/user-attachments/assets/da5ec32d-eb4d-4e10-b582-38e75d4e19e8)

### 🤬 Actual Behavior

표시되지 않음.
설정에서 내비게이션 바 쪽에 들어가 배경을 재설정해도 마찬가지임.

### 💻 Frontend Environment

```markdown
* Model and OS of the device(s):
* Browser: chrome 123.0.6312.58
* Server URL: kokonect.link, p.in-c.xyz
* CherryPick: 4.14.0
```

### 🛰 Backend Environment (for server admin)

```markdown
* Installation Method or Hosting Service:
* CherryPick:
* Node:
* PostgreSQL:
* Redis:
* OS and Architecture:
```

### Do you want to address this bug yourself?

- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by noridev** [comment]
9d2b4d5ffc15c35541ea72b29ea778f0e138a0fa 에서 수정되었습니다. 감사합니다! 🙏🙏
