### ISSUE TITLE
Pinned list does not display, shows error message.

### ISSUE THREAD

**Issue by damiandbc** [kokonect-link/cherrypick#546]
After the recent update, the pinned list function stopped working. It doesn't matter which list I use it displays an error message.

![image](https://github.com/user-attachments/assets/2e245a87-170c-4c03-858d-671075e2f032)

Here is the error:

"Timeline disabled

You cannot use this timeline under your current roles."

The list displays fine when I choose it from the Lists menu.

**Comment by noridev** [comment]
The error has been fixed in afbce36da9d4302f853df60c2cef6c67abd87dea. Thank you! 🙏
