### ISSUE TITLE
カスタム絵文字を何個も選択して一斉に入れれるように。

### ISSUE THREAD

**Issue by alice-coders** [kokonect-link/cherrypick#78]
## Summary
Misskey 13.13.0 （13.12.2）以前のようにカスタム絵文字を、何個も選択して一斉に、入れれるようにしてほしいです。
今でも、たくさんの鯖缶がこの問題に苦しんでいると思います。この機能を搭載することによって、CherryPickを採用しようという人が増えるし、便利になるのでは？ということで、提案させていただきました。
一応韓国語も置いときます。
Misskey 13.13.0(13.12.2) 이전처럼 사용자 지정 이모티콘을 여러 개 선택해서 한 번에 넣을 수 있었으면 좋겠습니다.
지금도 많은 서버 관리자들이 이 문제로 어려움을 겪고 있는 것 같습니다. 이 기능을 탑재하면 더 많은 사람들이 CherryPick을 사용하게 될 것이고, 더 편리하게 사용할 수 있지 않을까? 라는 생각에 제안하게 되었습니다.
検討よろしくお願いします。

**Comment by noridev** [comment]
ご提案ありがとうございます！
確かに便利だと思いますが、zipでまとめてインポートする現在の方法が、追加したい機能と重複するので、ご意見を伺いたいです。
zipでまとめてからインポートする方式はやはり面倒ですか？

**Comment by alice-coders** [comment]
私からすると、ZIPに圧縮して送信という手間がとても面倒だと感じています。　
スマホからやる身としては追加アプリなどを使わないといけないので、とても、手間が増えます。
なので、複数導入できたほうが良いわけです。
そちらのほうが、手軽ですから。

**Comment by noridev** [comment]
確かにスマホでは不便かも
